services:
  - type: web
    name: L&FAPP
    runtime: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn LOSTANDFOUND.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3

      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

      - key: SECRET_KEY
        generateValue: true

      - key: WEB_CONCURRENCY
        value: 4