services:
  - type: web
    name: lostandfound
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    pythonVersion: 3.11
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
    autoDeploy: true
