# Generated by Django 6.0.4 on 2026-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('faculty', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('description_of_item', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='writers_pics')),
                ('status', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
