# Generated by Django 6.0.4 on 2026-05-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='status',
        ),
    ]
