# Generated by Django 6.0.4 on 2026-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_submit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='status',
            field=models.CharField(blank=True, choices=[('Lost', 'Lost'), ('Found', 'Found')], null=True),
        ),
    ]
